<?php
	#AUTOGENERATED BY HYBRIDAUTH 2.1.2 INSTALLER - Monday 20th of January 2014 10:13:26 PM

/*!
* HybridAuth
* http://hybridauth.sourceforge.net | http://github.com/hybridauth/hybridauth
* (c) 2009-2012, HybridAuth authors | http://hybridauth.sourceforge.net/licenses.html
*/

// ----------------------------------------------------------------------------------------
//	HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------

return 
	array(
		"base_url" => "http://anclave.com/hybridauth/", 

		"providers" => array ( 
			// openid providers
			"OpenID" => array (
				"enabled" => false
			),

			"AOL"  => array ( 
				"enabled" => false 
			),

			"Yahoo" => array ( 
				"enabled" => false,
				"keys"    => array ( "id" => "", "secret" => "" )
			),

			"Google" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "815681941156-0afq1jvitfbscgmbhaq9tffopr3fmj43.apps.googleusercontent.com", "secret" => "XLspcIFlBDiwmCE5nH1Leg4J" )
			),

			"Facebook" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "576945409060898", "secret" => "efb374688fdb0369bc1394af947f56e5" )
			),

			"Twitter" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "130439073-VEMuLIB36H1apllOvV3Y3kaE68Sga0Q0lhS19o0V", "secret" => "2ptllh9WT0BANC9zOhEauNv9ZiSU19pasitfSGfTtkmgH" )
			),

			// windows live
			"Live" => array ( 
				"enabled" => false,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),

			"MySpace" => array ( 
				"enabled" => false,
				"keys"    => array ( "key" => "", "secret" => "" ) 
			),

			"LinkedIn" => array ( 
				"enabled" => false,
				"keys"    => array ( "key" => "", "secret" => "" ) 
			),

			"Foursquare" => array (
				"enabled" => false,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),
		),

		// if you want to enable logging, set 'debug_mode' to true  then provide a writable file by the web server on "debug_file"
		"debug_mode" => false,

		"debug_file" => ""
	);
